ProyectoFinal/Project/urls.py
from django.urls import path
from .views import *

app_name = 'Project'

urlpatterns = [
    path('', ProductList.as_view(), name='home'),
    path('about/', about, name='about'),
    path('not-found/', notfound, name='not-found'),
    path('my-products/', MyProductList.as_view(), name='my-products'),
    path('product/<pk>', ProductDetail.as_view(), name='detail'),
    path('like/', like, name='like'),
    path('comment/', comment, name='comment'),
    path('comment-list/', CommentList.as_view(), name='comment-list'),
    path('new-product/', NewProduct.as_view(), name='new-product'),
    path('update-product/<pk>', UpdateProduct.as_view(), name='update-product'),
    path('delete-product/<pk>', DeleteProduct.as_view(), name='delete-product'),
    path('delete-comment/<pk>', DeleteComment.as_view(), name='delete-comment'),
    path('search/', search, name='search'),
    
    
]

ProyectoFinal/ProyectoFinal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Project.urls', namespace='project')),
    path('', include('Accounts.urls', namespace='accounts')),
    path('', include('Messages.urls', namespace='messages')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ProyectoFinal/Project/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length=50)
    image = models.ImageField(upload_to='products/', null=True, blank=True, default='products/default_product.png')
    description = models.TextField()
    price = models.FloatField()
    location = models.CharField(max_length=50)
    available = models.BooleanField(default=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ('-date',)

    def __str__(self):
        return self.description
    
    def get_absolute_url(self):
        return reverse("detail", args=[str(self.id)])
    
    @property
    def get_comments(self):
        own_comments = Comment.objects.filter(product=self)
        return own_comments
    
    
class Comment(models.Model):
    comment = models.TextField(blank=True)
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name='user_like')
    product = models.ForeignKey(Product, null=True, blank=True, on_delete=models.CASCADE, related_name='comments')  
    date = models.DateTimeField(auto_now_add=True)  
    user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.CASCADE)
    
    def __str__(self):
        return f'{self.user} --> {self.comment}'

ProyectoFinal/Project/forms.py
from django import forms
from .models import Product, Comment

class ProductForm(forms.ModelForm):
    
    class Meta:
        model = Product
        fields = "__all__"
        exclude = ['date', 'user']

    

ProyectoFinal/Project/views.py
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse, reverse_lazy
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

from .models import Product, Comment
from .forms import ProductForm

# Create your views here.
def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def notfound(request):
    return render(request, 'notfound.html')

class ProductList(ListView):
    
    model = Product
    template_name = 'home.html'
    
class MyProductList(LoginRequiredMixin, ListView):
    
    model = User
    template_name = 'product-list.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['products'] = Product.objects.all()
    
class ProductDetail(DetailView):
    
    model = Product
    template_name = 'product-detail.html'
    
class NewProduct(LoginRequiredMixin, CreateView):

    model = Product
    template_name = 'new-product.html'
    success_url = reverse_lazy('project:my-products')
    form_class = ProductForm
    
    def form_valid(self, form):
        form.instance.user = self.request.user
        form.save()
        return super(NewProduct, self).form_valid(form)
    
class UpdateProduct(LoginRequiredMixin, UpdateView):

    login_url = 'login/'
    model = Product
    template_name = 'update-product.html'
    success_url = reverse_lazy('project:my-products')
    fields = ['name', 'image', 'description', 'price', 'location', 'available']
    
class DeleteProduct(LoginRequiredMixin, DeleteView):

    model = Product
    template_name = 'delete-product.html'
    success_url = reverse_lazy('project:my-products')
    
class CommentList(LoginRequiredMixin, ListView):
  
    model = Product
    template_name = 'comment-list.html'
  
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comments'] = Comment.objects.all()
       
        
    
class DeleteComment(LoginRequiredMixin, DeleteView):

    model = Comment
    template_name = 'delete-comment.html'
    success_url = reverse_lazy('project:comment-list')
    
@login_required(login_url='login/')
def like(request):
    comment_id = request.GET['comment_id']
    comment = get_object_or_404(Comment, id=comment_id)
    if request.user in comment.likes.all():
        comment.likes.remove(request.user)
        liked=False
    else:
        comment.likes.add(request.user)
        liked=True
    
    comment.save()
    likes=comment.likes.count()
    response = JsonResponse({'liked':liked, 'likes':likes})
    return response
    
@login_required(login_url='login/')
def comment(request):
    product_id = request.GET['product_id']
    product = get_object_or_404(Product, id=product_id)
    comment_data = request.GET['comment']
    comment = Comment(product = product, user = request.user, comment = comment_data)
    comment.save()
    response = JsonResponse({'comment' : comment_data})
    return response


def search(request):
    
    if request.GET['name']:
        searched_product = request.GET['name']
        response = Product.objects.filter(name__icontains = searched_product)

        return render(request, 'search.html', {'products': response, 'name': searched_product})

    response = 'Could not find the product'
    return HttpResponse(response)

ProyectoFinal/Project/templates/Project/home.html
{% extends 'Project/main.html' %}

{% block title %}
Home
{% endblock %}

{% block header %}
Welcome to the Coderhouse's Marketplace
{% endblock %}

{% block subheader %}
Take a look to the products and get the perfect one for you
{% endblock %}

{% block content %}
<section class="py-5">
    <div class="container px-4 px-lg-5 mt-5">
        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">

            {% for product in object_list %}
            <div class="col mb-5">
                <div class="card h-100">
                    <!-- Product image-->
                    <img class="card-img-top" src="{{ product.image.url }}" alt="{{ product.name }}" />
                    <!-- Product details-->
                    <div class="card-body p-4">
                        <div class="text-center">
                            <!-- Product name-->
                            <h5 class="fw-bolder">{{ product.name }}</h5>
                            <!-- Product price-->
                            $ {{ product.price }}
                        </div>
                    </div>
                    <!-- Product actions-->
                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                        <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'detail' product.id %}">More</a></div>
                    </div>
                </div>
            </div>
            {% endfor %}
            
        </div>
    </div>
</section>

{% endblock %}

ProyectoFinal/Project/templates/Project/login.html
{% extends 'Project/main.html' %}

{% block title %}
Signup
{% endblock %}

{% block header %}
Sign in
{% endblock %}

{% block content %}
<section class="mt-5 text-center">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">

                {% if message %}
                <p style="color: red;">{{ message }}</p>
                {% endif %}

                <form action="" method="POST">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button class="btn btn-outline-dark" type="submit">Sign In</button>
                </form>
                
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col-lg-12">
                <p class="">Don't have an account?</p>
                <a class="btn btn-outline-dark mb-2" href="{% url 'signup' %}">Sign up</a>
            </div>
        </div>
    </div>
</section>
{% endblock %}

ProyectoFinal/Project/templates/Project/logout.html
{% extends 'Project/main.html' %}

{% block title %}
Logout
{% endblock %}

{% block header %}
Logout
{% endblock %}

{% block content %}
<section class="mt-5 text-center">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">

                <h1>See you later...</h1>

                <a class="btn btn-outline-dark mb-2" href="{% url 'home' %}">Home</a>

            </div>
        </div>
    </div>
</section>

{% endblock %}

ProyectoFinal/Project/templates/Project/main.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block title %}{% endblock %}</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'Project/assets/favicon.ico' %}" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'Project/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light bg-light" style="position:fixed; width: 100vw;">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{% url 'home' %}">Coderhouse Marketplace</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-0 mb-lg-0 ms-lg-5">
                        {% if user.is_authenticated %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Shop</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="{% url 'my-products' %}">My Products</a></li>
                                <li><hr class="dropdown-divider" /></li>
                                <li><a class="dropdown-item" href="{% url 'home' %}">My Comments</a></li>
                                <li><hr class="dropdown-divider" /></li>
                                <li><a class="dropdown-item" href="{% url 'home' %}">Messages</a></li>
                            </ul>
                        </li>
                        {% else %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="{% url 'login' %}" role="button" data-bs-toggle="dropdown" aria-expanded="false">Shop</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="{% url 'login' %}">My Products</a></li>
                                <li><hr class="dropdown-divider" /></li>
                                <li><a class="dropdown-item" href="{% url 'login' %}">My Comments</a></li>
                                <li><hr class="dropdown-divider" /></li>
                                <li><a class="dropdown-item" href="{% url 'login' %}">Messages</a></li>
                            </ul>
                        </li>
                        {% endif %}
                        <li class="nav-item"><a class="nav-link" href="#!">About</a></li>
                    </ul>
                    <form class="d-flex">
                        {% if user.is_authenticated %}
                        <a href="{% url 'user-edit' %}"><img src="{{ user.avatar.image.url }}" class="rounded-circle mt-1" height="50px" width="50px" alt="{{ user.username }}"></a>
                        <a class="btn btn-outline-dark m-2" href="{% url 'logout' %}">
                            Logout
                        </a>
                        {% else %}
                        <a class="btn btn-outline-dark m-2" href="{% url 'login' %}">
                            Login
                        </a>
                        {% endif %}
                    </form>
                </div>
            </div>
        </nav>
        <!-- Header-->
        <header class="bg-dark py-5">
            <div class="container px-4 px-lg-5 my-5">
                <div class="text-center text-white">
                    <h1 class="display-4 fw-bolder">{% block header %}{% endblock %}</h1>
                    <p class="lead fw-normal text-white-50 mb-0">{% block subheader %}{% endblock %}</p>
                </div>
            </div>
        </header>
        <!-- Section-->
       

        {% block content %}

        {% endblock %}

        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container">
                <div class="row">             
                  
                        <ul class="list-inline m-0">
                            <li class="list-inline-item me-4 ">
                                <a href="https://www.linkedin.com/in/crismurua/"><i class="bi-linkedin fs-3 text-white"></i></a>
                            </li>
                            <li class="list-inline-item me-4">
                                <a href="https://github.com/Crismurua"><i class="bi-github fs-3 text-white"></i></a>
                            </li>
                            <li class="list-inline-item">
                                <a href="https://calendly.com/cristianmurua"><i class="bi-calendar-check-fill fs-3 text-white"></i></a>
                            </li>
                        </ul>
                    
                </div>
            </div>
            
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>

ProyectoFinal/Project/templates/Project/new-product.html
{% extends 'Project/main.html' %}

{% block title %}
New Product
{% endblock %}

{% block header %}

Publish your products

{% endblock %}


{% block content %}
<section class="mt-2 text-center">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                
                <form class="m-4" action="" method="POST">
                    {% csrf_token %}
                    <table class="d-flex justify-content-center">
                        {{ form.as_table }}
                    </table>
                    <input class="btn btn-outline-dark m-2" type="submit" value="Confirm">
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

ProyectoFinal/Project/templates/Project/product-detail.html
{% extends 'Project/main.html' %}

{% block title %}
Details
{% endblock %}

{% block header %}
Product Detail
{% endblock %}

{% block subheader %}
See the complete info about the product
{% endblock %}

{% block content %}
<section class="py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="row gx-4 gx-lg-5 align-items-center">
            <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0" src="{{ product.image.url }}" alt="{{ product.name }}" /></div>
            <div class="col-md-6">
                <div class="small mb-1">Seller: {{ product.user.username }}</div>
                <h1 class="display-5 fw-bolder">{{ product.name }}</h1>
                <div class="fs-1 mb-5">
                    <strong><span style="color: green;">$ {{ product.price }}</span></strong>
                    
                </div>
                <p class="lead">{{ product.description }}</p>
                <div class="d-flex">
                    <div class="small m-2">{{ product.location }}</div>
                    {% if product.available == True %}
                    <div class="small m-2">Available</div>
                    {% else %}
                    <div class="small m-2">Not Available</div>
                    {% endif %}
                </div>
            </div>
        </div>
        
    </div>
</section>

<!-- Comments -->
<section class="py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="row gx-4 gx-lg-5 align-items-center">
           {% if product.comment_set.all %}
            {% for comment in product.comment_set.all %}
            <div class="media mb-2">

                {% if comment.user.avatar %}
                    <img class="d-flex mr-2 rounded-circle" width="50px" height="50px" src="{{ comment.user.image.url }}" alt="{{ user.username }}">
                {% else %}
                    <img class="d-flex mr-2 rounded-circle" src="avatars/blank.png" alt="">
                {% endif %}
    
                <div class="media-body">
                    <h5 class="mt-0">{{comment.user.username}}</h5>
                    {{comment.comment}}
                </div>
            </div>

            {% endfor %}
           {% endif %} 
        </div>
        <a href="{% url 'new-comment' %}">
            <button class="btn btn-outline-dark flex-shrink-0 m-3" type="">
                <i class="bi-chat-left-dots-fill me-1"></i>
                Comment
            </button>
        </a>
    </div>
</section>


{% endblock %}

ProyectoFinal/Project/templates/Project/product-list.html
{% extends 'Project/main.html' %}

{% block title %}
My Products
{% endblock %}

{% block header %}
My Products
{% endblock %}

{% block subheader %}
See your published products and edit them
{% endblock %}

{% block content %}
<section class="py-5">
    <div class="container px-4 px-lg-5 mt-5">
        <a href="{% url 'new-product' %}"><button class="btn btn-outline-dark m-2">+ New</button></a>
        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">


            {% if user.product_set.all %}
            {% for product in user.product_set.all %}
            <div class="col mb-5">
                <div class="card h-100">
                    <!-- Product image-->
                    <img class="card-img-top" src="{{ product.image.url }}" alt="{{ product.name }}" />
                    <!-- Product details-->
                    <div class="card-body p-4">
                        <div class="text-center">
                            <!-- Product name-->
                            <h5 class="fw-bolder">{{ product.name }}</h5>
                            <!-- Product price-->
                            $ {{ product.price }}
                        </div>
                    </div>
                    <!-- Product actions-->
                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                        <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'detail' product.id %}">More</a></div>
                    </div>
                </div>
            </div>
            {% endfor %}
            {% endif %}
            
        </div>
    </div>
</section>

{% endblock %}

ProyectoFinal/Project/templates/Project/signup.html
{% extends 'Project/main.html' %}

{% block title %}
Signup
{% endblock %}

{% block header %}
Sign Up
{% endblock %}

{% block subheader %}
Create your account to find your dream product or to sell someone else one
{% endblock %}

{% block content %}
<section class="mt-2 text-center">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">

                {% if message %}
                <p style="color: red;">{{ message }}</p>
                {% endif %}

                <form action="" method="POST">
                    {% csrf_token %}
                    <table class="d-flex justify-content-center">
                    {{ form.as_table }}
                    {{ form2.as_table }}
                    </table>
                    <button class="btn btn-outline-dark m-2" type="submit">Sign Up</button>
                </form>
                
            </div>
        </div>
    </div>
</section>
{% endblock %}

ProyectoFinal/Project/templates/Project/user-edit.html
{% extends 'Project/main.html' %}

{% block title %}
Profile
{% endblock %}

{% block header %}

Welcome {{ user }}!

{% endblock %}

{% block subheader %}
Edit your profile
{% endblock %}

{% block content %}
<section class="mt-2 text-center">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <a href="{% url 'avatar-edit' %}"><img src="{{ user.avatar.image.url }}" class="rounded-circle" height="200px" width="200px" alt=""></a>
                
                <form class="m-4" action="" method="POST">
                    {% csrf_token %}
                    <table class="d-flex justify-content-center">
                        {{ form.as_table }}
                    </table>
                    <input class="btn btn-outline-dark m-2" type="submit" value="Confirm">
                </form>

                <a href="{% url 'user-extra' %}"><button class="btn btn-outline-dark m-2">Extra Fields</button></a>
            </div>
        </div>
    </div>
</section>
{% endblock %}

ProyectoFinal/Project/templates/Project/user-extra.html
{% extends 'Project/main.html' %}

{% block title %}
Profile
{% endblock %}

{% block header %}

Welcome {{ user }}!

{% endblock %}

{% block subheader %}
Edit extra fields
{% endblock %}

{% block content %}
<section class="mt-2 text-center">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <a href="{% url 'avatar-edit' %}"><img src="{{ user.avatar.image.url }}" class="rounded-circle" height="200px" width="200px" alt=""></a>
                
                <form class="m-4" action="" method="POST">
                    {% csrf_token %}
                    <table class="d-flex justify-content-center">
                        {{ form.as_table }}
                    </table>
                    <input class="btn btn-outline-dark m-2" type="submit" value="Confirm">
                </form>

            </div>
        </div>
    </div>
</section>
{% endblock %}