ProyectoFinal/Accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from .views import *
from Accounts.views import *

app_name = 'Accounts'

urlpatterns = [
    path('signup/', signup, name='signup'),
    path('login/', login_request, name='login'),
    path('logout/', LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('user-edit/', user_edit, name='user-edit'),
    path('user-extra/', user_extra, name='user-extra'),
    path('avatar-edit/', upload_avatar, name='avatar-edit'),  
    path('user-detail/<pk>', UserDetail.as_view(), name='user-detail'),    
]

ProyectoFinal/Messages/urls.py
from django.urls import path, re_path
from .views import *

app_name = 'Messages'

UUID_CHAT_REGEX = r'canal/(?P<pk>[a-f0-9]{8}-?[a-f0-9]{4}-?4[a-f0-9]{3}-?[89ab][a-f0-9]{3}-?[a-f0-9]{12})'

urlpatterns = [
    re_path(UUID_CHAT_REGEX, ChatDetailView.as_view()),
	path("dm/<str:username>", private_messages, name='privatems'),
	path("ms/<str:username>", DetailMs.as_view(), name="detailms"),
	path("inbox/", Inbox.as_view(), name="inbox"),
]

ProyectoFinal/Project/urls.py
from django.urls import path
from .views import *

app_name = 'Project'

urlpatterns = [
    path('', ProductList.as_view(), name='home'),
    path('about/', about, name='about'),
    path('not-found/', notfound, name='not-found'),
    path('my-products/', MyProductList.as_view(), name='my-products'),
    path('product/<pk>', ProductDetail.as_view(), name='detail'),
    path('like/', like, name='like'),
    path('comment/', comment, name='comment'),
    path('comment-list/', CommentList.as_view(), name='comment-list'),
    path('new-product/', NewProduct.as_view(), name='new-product'),
    path('update-product/<pk>', UpdateProduct.as_view(), name='update-product'),
    path('delete-product/<pk>', DeleteProduct.as_view(), name='delete-product'),
    path('delete-comment/<pk>', DeleteComment.as_view(), name='delete-comment'),
    path('search/', search, name='search'),
    
    
]

ProyectoFinal/ProyectoFinal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Project.urls', namespace='project')),
    path('', include('Accounts.urls', namespace='accounts')),
    path('', include('Messages.urls', namespace='messages')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ProyectoFinal/Messages/models.py
from django.db import models
import uuid
from django.conf import settings
from django.contrib.auth.models import User
from django.db.models import Count

# Create your models here.
class ModelBase(models.Model):
    id = models.UUIDField(default=uuid.uuid4, primary_key=True, db_index=True, editable=False)
    date = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    
    class Meta:
        abstract = True
        
class ChatMessage(ModelBase):
    chat = models.ForeignKey("Chat", on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    text = models.TextField()
    
class ChatUser(ModelBase):
    chat = models.ForeignKey("Chat", null=True, on_delete=models.SET_NULL)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    
class ChatQuerySet(models.QuerySet):

	def only_one(self):
		return self.annotate(num_users=Count("users")).filter(num_users=1)

	def only_two(self):
		return self.annotate(num_users= Count("users")).filter(num_users=2)

	def filter_username(self, username):
		return self.filter(chatuser__user__username=username)

class ChatManager(models.Manager):
    
    def get_queryset(self, *args, **kwargs):
        return ChatQuerySet(self.model, using=self._db)
    
    def filter_ms_private(self, username_a, username_b):
        return self.get_queryset().only_two().filter_username(username_a).filter_username(username_b)
    
    def get_ot_create_chat_current_user(self, user):
        qs = self.get_queryset().only_one().filter_username(user.username)
        if qs.exists():
            return qs.order_by("date").first, False
        
        chat_obj = Chat.objects.create()
        ChatUser.objects.create(user=user, chat=chat_obj)
        return chat_obj, True
	        

    def get_or_create_chat_ms(self, username_a, username_b):
        qs = self.filter_ms_private(username_a, username_b)
        if qs.exists():
            return qs.order_by("date").first(), False
        
        
        user_a, user_b = None, None
        try:
            user_a = User.objects.get(username=username_a)
        except User.DoesNotExist:
            return None, False
        
        try:
            user_b = User.objects.get(username=username_b)
        except User.DoesNotExist:
            return None, False
        
        if user_a == None or user_b ==None:
            return None, False
        
        obj_chat = Chat.objects.create()
        chat_user_a = ChatUser(user=user_a, chat=obj_chat)
        chat_user_b = ChatUser(user=user_b, chat=obj_chat)
        ChatUser.objects.bulk_create([chat_user_a, chat_user_b])
        return obj_chat, True
    
class Chat(ModelBase):
    users = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, through=ChatUser)
    objects = ChatManager()

ProyectoFinal/Project/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length=50)
    image = models.ImageField(upload_to='products/', null=True, blank=True, default='products/default_product.png')
    description = models.TextField()
    price = models.FloatField()
    location = models.CharField(max_length=50)
    available = models.BooleanField(default=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ('-date',)

    def __str__(self):
        return self.description
    
    def get_absolute_url(self):
        return reverse("detail", args=[str(self.id)])
    
    @property
    def get_comments(self):
        own_comments = Comment.objects.filter(product=self)
        return own_comments
    
    
class Comment(models.Model):
    comment = models.TextField(blank=True)
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name='user_like')
    product = models.ForeignKey(Product, null=True, blank=True, on_delete=models.CASCADE, related_name='comments')  
    date = models.DateTimeField(auto_now_add=True)  
    user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.CASCADE)
    
    def __str__(self):
        return f'{self.user} --> {self.comment}'

ProyectoFinal/templates/chat-detail.html
{% extends 'main.html' %}

{% block title %}
Messages
{% endblock %}

{% block header %}
Chat
{% endblock %}


{% block content %}

<style>

#contenedor_ms{
			width: 50%;
			height: calc(100vh);
			margin-top: 100px;
            padding: 50px;
            margin-left: auto;
            margin-right: auto;
			overflow-y: scroll;
			border: 1px solid black;
			background: lightgrey;
            display: flex;
            flex-direction: column;
            justify-content: center;
		}

.div_ms{
	width: 35%;
	margin: 2px auto;
	padding: 0.2rem 0.6rem 0.2rem 0.6rem; 
    
}

.my_messages{
			
			margin-right: 5px;
			background-color:rgb(100, 100, 100);
			color: #fff;
			border-bottom-left-radius: 16px;
			border-top-left-radius: 16px;
			border-top-right-radius: 16px;
		}

.your_messages{
	background: rgb(230, 236, 240);
	margin-left: 5px;
	border-bottom-right-radius: 16px;
	border-top-left-radius: 16px;
	border-top-right-radius: 16px;
}
 
.div_form_ms{
			
			margin-top: 5px;
			margin-bottom: 5px;
			margin-left: auto;
            margin-right: auto;
			
		}

#form_submit{
    
    display: flex;
    flex-direction: row;
    justify-content: center;
    align-items: center;
    max-height: 50px;
    
}
textarea {
    max-height: 50px;
    
}
header{
	display:none;
}



</style>


    <div class="container py-1"></div>   

        <div id="contenedor_ms">
            {% for message in object.chatmessage_set.all %}	
                <div class="div_ms {% if request.user == message.user %}my_messages
                {% else %} your_messages{% endif %}">
                    <small>{{message.user}}</small>
                    <p>{{message.text}}</p>
                    <small>{{message.date}}</small>
                </div>
        
            {% endfor %}
        </div>

        <div class="div_form_ms">
            <form id="form_submit" action="{{ request.path }}" method="POST">
                {% csrf_token %}
                <table>
                    {{form.as_table}}
                </table>
                <button type="submit" class="btn btn-outline-dark">
                    Send
                </button>
    
    
            </form>
    
        </div>




<script>

	const MsgForm = document.getElementById("form_submit")
	const msgContainer = document.getElementById("contenedor_ms")


	MsgForm.addEventListener("submit", (event) => {

		event.preventDefault()

		const  targetDate = event.target 
		const formData = new FormData(targetDate)

		const xhr = new XMLHttpRequest() // ajax fetch


		const endpoint = MsgForm.getAttribute("action")
		const method = MsgForm.getAttribute("method")
		xhr.open(method, endpoint)

		xhr.responseType = 'json'

		xhr.setRequestHeader("HTTP_X_REQUESTED_WITH", "XMLHttpRequest")
		xhr.setRequestHeader("X-Requested-With", "XMLHttpRequest")

		xhr.onload = () =>{

			console.log(xhr.status, xhr.response)

			if(xhr.status === 201){
				const respuestaData = xhr.response
				let actualMensajeHtml = msgContainer.innerHTML
				actualMensajeHtml += `<div class=''><b>${respuestaData.username}</b><p>${respuestaData.message}</p></div>` 
				msgContainer.innerHTML = actualMensajeHtml
				MsgForm.reset()
			}else if(xhr.status === 400){
				console.log(hxr.response)
			}else{
				alert("Something happend")
			}

		}

		xhr.send(formData)


	})
	


</script>

{% endblock %}

ProyectoFinal/templates/comment-list.html
{% extends 'main.html' %}

{% block title %}
My Comments
{% endblock %}

{% block header %}
My Comments
{% endblock %}

{% block subheader %}
See your published comments and delete them if you want
{% endblock %}

{% block content %}

<section class="py-5">
    <div class="container px-4 px-lg-5 mt-5">
        <div class="mb-1 column comment-div border-0">

            {% if user.comment_set.all %}
            {% for comment in user.comment_set.all %}
            <div id="{{ comment.id }}"class='d-flex justify-content-between col-5 p-0 m-1'>
                <strong>{{ comment.product.name }} : </strong> {{ comment.comment }}
            </div>
            {% endfor %}
            {% endif %}

        </div>
    </div>
</section>

{% endblock %}

ProyectoFinal/templates/delete-comment.html
{% extends 'main.html' %}

{% block title %}
My Comments
{% endblock %}

{% block header %}
Delete Comment
{% endblock %}

{% block subheader %}
Delete the Comment selected
{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="display-5 fw-bolder">Delete Comment</h1>
            <form method="POST">
            {% csrf_token %}
                <p class="lead">Sure you want to delete {{ comment.comment }}?</p>
                
                <input class="btn btn-outline-danger mt-auto" type="submit" value="Delete">
            </form>
        </div>
    </div>
</div>

{% endblock %}

ProyectoFinal/templates/home.html
{% extends 'main.html' %}

{% block title %}
Home
{% endblock %}

{% block header %}
Welcome to the Coderhouse's Marketplace
{% endblock %}

{% block subheader %}
Take a look to the products and get the perfect one for you
{% endblock %}

{% block content %}
<section class="py-5">
    <div class="container px-4 px-lg-5 mt-5">
        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">

            {% for product in object_list %}
            <div class="col mb-5">
                <div class="card h-100">
                    <!-- Product image-->
                    <img class="card-img-top" src="{{ product.image.url }}" alt="{{ product.name }}" />
                    <!-- Product details-->
                    <div class="card-body p-4">
                        <div class="text-center">
                            <!-- Product name-->
                            <h5 class="fw-bolder">{{ product.name }}</h5>
                            <!-- Product price-->
                            $ {{ product.price }}
                        </div>
                    </div>
                    <!-- Product actions-->
                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                        <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'project:detail' product.id %}">More</a></div>
                    </div>
                </div>
            </div>
            {% endfor %}
            
        </div>
    </div>
</section>

{% endblock %}

ProyectoFinal/templates/inbox.html
{% extends 'main.html' %}

{% block title %}
Messages
{% endblock %}

{% block header %}
Inbox
{% endblock %}

{% block subheader %}
Welcome {{ user.username }}
{% endblock %}

{% block content %}
<section class="py-5">
    <div class="container px-4 px-lg-5 mt-2">
        
        {% for inbox in inbox %}
        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
            {% for second_user in inbox.chatuser_set.all %}

                {% if second_user.user == request.user %}
                {% else %}
                    <a class="btn btn-outline-dark" href="{% url 'messages:detailms' second_user.user.username %}">
                        <p>
                            {{second_user.user}}
                        </p>
                        <small>
                            ({{inbox.chatmessage_set.count}}) Messages
                        </small>
                    </a>
                {% endif %}
            {% endfor %}

                    {% if inbox.chatmessage_set.count != 0 %}
                    <div class="div_ms_inbox">
                        
                        {% with last_message=inbox.chatmessage_set.last %}
            
                            <p>
                                Message: {{ last_message.text }}
                            </p>
            
                            <p>
                                User: {{ last_message.user }}
                            </p>
            
                        {% endwith %}
                    </div>	
                {% else %}
                    <p>
                        Not Messages
                    </p>
                {% endif %}
            
            
            
            </div>
            {% empty %}
            
            <h2>
                Empty Inbox
            </h2>

        </div>
        {% endfor %}
    </div>
</section>
{% endblock %}

ProyectoFinal/templates/login.html
{% extends 'main.html' %}

{% block title %}
Signup
{% endblock %}

{% block header %}
Sign in
{% endblock %}

{% block content %}
<section class="mt-5 text-center">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">

                {% if message %}
                <p style="color: red;">{{ message }}</p>
                {% endif %}

                <form action="" method="POST">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button class="btn btn-outline-dark" type="submit">Sign In</button>
                </form>
                
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col-lg-12">
                <p class="">Don't have an account?</p>
                <a class="btn btn-outline-dark mb-2" href="{% url 'accounts:signup' %}">Sign up</a>
            </div>
        </div>
    </div>
</section>
{% endblock %}

ProyectoFinal/templates/logout.html
{% extends 'main.html' %}

{% block title %}
Logout
{% endblock %}

{% block header %}
Logout
{% endblock %}

{% block content %}
<section class="mt-5 text-center">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">

                <h1>See you later...</h1>

                <a class="btn btn-outline-dark mb-2" href="{% url 'project:home' %}">Home</a>

            </div>
        </div>
    </div>
</section>

{% endblock %}

ProyectoFinal/templates/main.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block title %}{% endblock %}</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
        <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light bg-light" style="position:fixed; width: 100vw; z-index: 100;">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{% url 'project:home' %}">Coderhouse Marketplace</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-0 mb-lg-0 ms-lg-5">
                        {% if user.is_authenticated %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Shop</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="{% url 'project:my-products' %}">My Products</a></li>
                                <li><hr class="dropdown-divider" /></li>
                                <li><a class="dropdown-item" href="{% url 'project:comment-list' %}">My Comments</a></li>
                                <li><hr class="dropdown-divider" /></li>
                                <li><a class="dropdown-item" href="{% url 'messages:inbox' %}">Messages</a></li>
                            </ul>
                        </li>
                        {% else %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="{% url 'accounts:login' %}" role="button" data-bs-toggle="dropdown" aria-expanded="false">Shop</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="{% url 'accounts:login' %}">My Products</a></li>
                                <li><hr class="dropdown-divider" /></li>
                                <li><a class="dropdown-item" href="{% url 'accounts:login' %}">My Comments</a></li>
                                <li><hr class="dropdown-divider" /></li>
                                <li><a class="dropdown-item" href="{% url 'accounts:login' %}">Messages</a></li>
                            </ul>
                        </li>
                        {% endif %}

                        <li class="nav-item"><a class="nav-link" href="{% url 'project:not-found' %}">404</a></li>

                        <li class="nav-item"><a class="nav-link" href="{% url 'project:about' %}">About</a></li>
                    </ul>
                    <form class="d-flex">
                        {% if user.is_authenticated %}
                        <a href="{% url 'accounts:user-edit' %}">
                            
                            {% if user.avatar.image %}
                            <img src="{{ user.avatar.image.url }}" class="rounded-circle mt-1" height="50px" width="50px" alt="{{ user.username }}">
                            {% else %}
                            <img src="../media/avatar/blank.png" class="rounded-circle mt-1" height="50px" width="50px" alt="{{ user.username }}">
                            {% endif %}
                        
                        </a>
                        <a class="btn btn-outline-dark m-2" href="{% url 'accounts:logout' %}">
                            Logout
                        </a>
                        {% else %}
                        <a class="btn btn-outline-dark m-2" href="{% url 'accounts:login' %}">
                            Login
                        </a>
                        {% endif %}
                    </form>
                </div>
            </div>
        </nav>
        <!-- Header-->
        <header class="bg-dark py-4">
            <div class="container px-3 px-lg-5 my-5">
                <div class="text-center text-white pt-5">
                    <h1 class="display-4 fw-bolder">{% block header %}{% endblock %}</h1>
                    <p class="lead fw-normal text-white-50 mb-0">{% block subheader %}{% endblock %}</p>
                </div>
            </div>
        </header>
        <!-- Section-->
       

        {% block content %}

        {% endblock %}

        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container">
                <div class="row">             
                  
                        <ul class="list-inline m-0">
                            <li class="list-inline-item me-4 ">
                                <a href="https://www.linkedin.com/in/crismurua/" target="_bl
                                "><i class="bi-linkedin fs-3 text-white"></i></a>
                            </li>
                            <li class="list-inline-item me-4">
                                <a href="https://github.com/Crismurua" target="_bl
                                "><i class="bi-github fs-3 text-white"></i></a>
                            </li>
                            <li class="list-inline-item">
                                <a href="https://calendly.com/cristianmurua" target="_bl
                                "><i class="bi-calendar-check-fill fs-3 text-white"></i></a>
                            </li>
                        </ul>
                    
                </div>
            </div>
            
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>

        <script>
            $(document).on('click', '.like-button', function (e) {
              e.preventDefault();
              var comment_id = $(this).data('comment');
              $.ajax({
                type: 'GET',
                url: '{% url "project:like" %}',
                data: {
                  comment_id: comment_id
                },
                success: function (response) {
                  $('#' + comment_id).load(location.href + ' #' + comment_id)
                },
                error: function (xhr, errmsg, err) {}
              });
            })
            
            $(document).on('click', '.comment-button', function (e) {
              e.preventDefault();
              var product_id = $(this).data('product');
              var comment = $('#comment' + product_id).prop('value')
              if (comment != '') {
                $.ajax({
                  type: 'GET',
                  url: '{% url "project:comment" %}',
                  data: {
                    product_id: product_id,
                    comment: comment
                  },
                  success: function (response) {
                    $(".comment-div").load(location.href + " .comment-div")
                    $("#comment_form")[0].reset()
                  },
                  error: function (xhr, errmsg, err) {}
                });
              }
            })
          </script>
    </body>
</html>

ProyectoFinal/templates/new-product.html
{% extends 'main.html' %}

{% block title %}
New Product
{% endblock %}

{% block header %}

Publish your products

{% endblock %}


{% block content %}
<section class="mt-2 text-center">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                
                <form class="m-4" action="" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <table class="d-flex justify-content-center">
                        {{ form.as_table }}
                    </table>
                    <input class="btn btn-outline-dark m-2" type="submit" value="Confirm">
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

ProyectoFinal/templates/notfound.html
{% extends 'main.html' %}

{% block title %}
404 Not Found
{% endblock %}

{% block header %}
Code 404 Not Found
{% endblock %}

{% block subheader %}
{% endblock %}

{% block content %}
<section class="py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center">
            <img style="width:500px; height:500px;" src="https://img.freepik.com/vector-premium/concepto-mantenimiento-sitio-web-construccion-sitio-ilustracion-isometrica-sobre-fondo-blanco_393343-393.jpg" alt="500px Men At Work Sign Svg">
        </div>
    </div>
</section>
{% endblock %}

ProyectoFinal/templates/update-product.html
{% extends 'main.html' %}

{% block title %}
My Products
{% endblock %}

{% block header %}

Welcome {{ user }}!

{% endblock %}

{% block subheader %}
Edit your product
{% endblock %}

{% block content %}
<section class="mt-2 text-center">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <img src="{{ product.image.url }}" class="border-dark" height="200px" width="200px" alt="">
                
                <form class="m-4" action="" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <table class="d-flex justify-content-center">
                        {{ form.as_table }}
                    </table>
                    <input class="btn btn-outline-dark m-2" type="submit" value="Confirm">
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

ProyectoFinal/templates/user-edit.html
{% extends 'main.html' %}

{% block title %}
Profile
{% endblock %}

{% block header %}

Welcome {{ user }}!

{% endblock %}

{% block subheader %}
Edit your profile
{% endblock %}

{% block content %}
<section class="mt-2 text-center">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <a href="{% url 'accounts:avatar-edit' %}">
                    {% if user.avatar.image %}
                    <img src="{{ user.avatar.image.url }}" class="rounded-circle" height="200px" width="200px" alt="">
                    {% else %}
                    <img src="../media/avatar/blank.png" class="rounded-circle" height="200px" width="200px" alt="">
                    {% endif %}
                </a>
                
                <form class="m-4" action="" method="POST">
                    {% csrf_token %}
                    <table class="d-flex justify-content-center">
                        {{ form.as_table }}
                    </table>
                    <input class="btn btn-outline-dark m-2" type="submit" value="Confirm">
                </form>

                <a href="{% url 'accounts:user-extra' %}"><button class="btn btn-outline-dark m-2">Extra Fields</button></a>
            </div>
        </div>
    </div>
</section>
{% endblock %}

ProyectoFinal/templates/user-extra.html
{% extends 'main.html' %}

{% block title %}
Profile
{% endblock %}

{% block header %}

Welcome {{ user }}!

{% endblock %}

{% block subheader %}
Edit extra fields
{% endblock %}

{% block content %}
<section class="mt-2 text-center">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <a href="{% url 'accounts:avatar-edit' %}">
                    {% if user.avatar.image %}
                    <img src="{{ user.avatar.image.url }}" class="rounded-circle" height="200px" width="200px" alt="">
                    {% else %}
                    <img src="../media/avatar/blank.png" class="rounded-circle" height="200px" width="200px" alt="">
                    {% endif %}
                </a>
                
                <form class="m-4" action="" method="POST">
                    {% csrf_token %}
                    <table class="d-flex justify-content-center">
                        {{ form.as_table }}
                    </table>
                    <input class="btn btn-outline-dark m-2" type="submit" value="Confirm">
                </form>

            </div>
        </div>
    </div>
</section>
{% endblock %}